<?php

ob_start();
?>
<main>
    <section id="newarticle">
        <fieldset>
            <legend>Article</legend>
            <form action="index.php?action=newPost" method="post" >
                <input type="text" name="title">
                <textarea name="mainText"></textarea>
                <select name="authorId">
                    <?php
                        foreach($authorInfo as $author) {
                            echo '<option name="authorId" value="'.$author['Id']. '">' . $author['FirstName'].' '. $author['LastName'] . '</option>';
                        }
                    ?>
                </select>
                <select name="categoryId">
                    <?php
                    foreach($categoryInfo as $category) {
                        echo '<option name="authorId" value="'.$category['Id']. '">' . $category['Name'] . '</option>';
                    }
                    ?>
                </select>
                <input type="submit">
            </form>
        </fieldset>
    </section>
</main>

<?php
$body = ob_get_clean();

include 'template.phtml';
?>
